#!/bin/bash
logger "Running cleanup_tikz"
find /var/www/html/tikz/tmp -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "live_*" -mmin +1 -exec rm {} \;
find /var/www/html/tikz -name "preview_*" -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "work_*" -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "tikztest_*" -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "nocontext_*" -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "submitted_*" -mmin +60 -exec rm {} \;
find /var/www/html/tikz -name "template_*" -mtime +90 -exec rm {} \;
